export type DebugState = {
  fps: number;
  width: number;
  height: number;
  scrollSpeed: number;
  loadedSprites: number;
  activeResources: number;
  activeWolves: number;
  nextResourceSpawn: number;
  nextWolfSpawn: number;
  runNumber: number;
  effectiveResourceAmountMin: number;
  effectiveResourceAmountMax: number;
  effectiveWolfPackSizeMin: number;
  effectiveWolfPackSizeMax: number;
  effectiveResourceSpawnInterval: number;
  effectiveWolfSpawnInterval: number;
  wolfHpBonus: number;
  wolfDamageBonus: number;
  wolfAttackSpeedBonus: number;
  gazeMode: string;
  targetsInsideCone: number;
  selectedTarget: string;
  lastCommandInput: string;
  wood: number;
  ore: number;
  cartHp: number;
  cartMaxHp: number;
  livingWarriors: number;
  totalWarriors: number;
  livingGatherers: number;
  totalGatherers: number;
  availableWarriors: number;
  assignedWarriors: number;
  availableGatherers: number;
  assignedGatherers: number;
  lastAssignmentResult: string;
  activeGatherers: number;
  gatheredResource: string;
  activeCombats: number;
  wolvesTargetingCart: number;
  deadWarriors: number;
  deadGatherers: number;
  gameOver: boolean;
  runPhase: "running" | "resurrection" | "upgrade" | "scalingSummary" | "gameOver";
  runTimeRemaining: number;
  runCompleted: boolean;
};

export const defaultDebugState: DebugState = {
  fps: 0,
  width: 0,
  height: 0,
  scrollSpeed: 0,
  loadedSprites: 0,
  activeResources: 0,
  activeWolves: 0,
  nextResourceSpawn: 0,
  nextWolfSpawn: 0,
  runNumber: 1,
  effectiveResourceAmountMin: 1,
  effectiveResourceAmountMax: 10,
  effectiveWolfPackSizeMin: 3,
  effectiveWolfPackSizeMax: 7,
  effectiveResourceSpawnInterval: 4,
  effectiveWolfSpawnInterval: 6,
  wolfHpBonus: 0,
  wolfDamageBonus: 0,
  wolfAttackSpeedBonus: 0,
  gazeMode: "default",
  targetsInsideCone: 0,
  selectedTarget: "none",
  lastCommandInput: "none",
  wood: 0,
  ore: 0,
  cartHp: 20,
  cartMaxHp: 20,
  livingWarriors: 0,
  totalWarriors: 0,
  livingGatherers: 0,
  totalGatherers: 0,
  availableWarriors: 0,
  assignedWarriors: 0,
  availableGatherers: 0,
  assignedGatherers: 0,
  lastAssignmentResult: "none",
  activeGatherers: 0,
  gatheredResource: "none",
  activeCombats: 0,
  wolvesTargetingCart: 0,
  deadWarriors: 0,
  deadGatherers: 0,
  gameOver: false,
  runPhase: "running",
  runTimeRemaining: 60,
  runCompleted: false,
};
