export const RESOURCE_AMOUNT_GROWTH_PER_SUCCESSFUL_RUN = 1;
export const WOLF_PACK_GROWTH_PER_SUCCESSFUL_RUN = 1;
export const WOLF_SPAWN_INTERVAL_REDUCTION_PER_SUCCESSFUL_RUN = 0.3;
export const RESOURCE_SPAWN_INTERVAL_REDUCTION_PER_SUCCESSFUL_RUN = 0.2;
export const MIN_WOLF_SPAWN_INTERVAL_SECONDS = 2;
export const MIN_RESOURCE_SPAWN_INTERVAL_SECONDS = 1;
export const WOLF_STAT_BONUS_PER_SUCCESSFUL_RUN = 1;
