export const WARRIOR_RUN_SPEED_MULTIPLIER = 4;
export const WARRIOR_BASE_HP = 7;
export const WARRIOR_DAMAGE = 2;
export const WARRIOR_ATTACKS_PER_SECOND = 2;
export const WARRIOR_REGENERATION_PER_SECOND = 0.5;
